local M = {}

-- Parses .nvim/editor.conf (INI format with [sections]) from the project root.
-- Returns a nested table: config["section"]["key"] = "value"
local function parse(path)
  local result = {}
  local section = nil
  for line in io.lines(path) do
    line = line:match("^%s*(.-)%s*$")
    if line == "" or line:match("^[;#]") then
      -- skip blank lines and comments
    elseif line:match("^%[(.+)%]$") then
      section = line:match("^%[(.+)%]$")
      result[section] = result[section] or {}
    elseif section and line:match("^(.-)%s*=%s*(.*)$") then
      local k, v = line:match("^(.-)%s*=%s*(.*)$")
      result[section][k] = v
    end
  end
  return result
end

-- Finds .nvim/editor.conf by walking up from cwd.
local function find_conf()
  local dir = vim.fn.getcwd()
  while true do
    local candidate = dir .. "/.nvim/editor.conf"
    if vim.fn.filereadable(candidate) == 1 then
      return candidate
    end
    local parent = vim.fn.fnamemodify(dir, ":h")
    if parent == dir then return nil end
    dir = parent
  end
end

local _cache = nil

-- Returns the parsed config table, or {} if no editor.conf found.
function M.load()
  if _cache then return _cache end
  local path = find_conf()
  _cache = path and parse(path) or {}
  return _cache
end

-- Shorthand: M.get("dap", "remote") → config["dap"]["remote"] or nil
function M.get(section, key)
  local cfg = M.load()
  return cfg[section] and cfg[section][key] or nil
end

-- Clears the cache (useful after :ConfigInit or manual edits).
function M.reload()
  _cache = nil
  return M.load()
end

-- Creates .nvim/editor.conf in cwd with a starter template.
function M.init()
  local nvim_dir = vim.fn.getcwd() .. "/.nvim"
  local conf_path = nvim_dir .. "/editor.conf"

  if vim.fn.filereadable(conf_path) == 1 then
    vim.notify("editor.conf already exists: " .. conf_path, vim.log.levels.WARN)
    return
  end

  vim.fn.mkdir(nvim_dir, "p")

  local template = table.concat({
    "# Project-specific Neovim config",
    "# Generated by :ConfigInit",
    "",
    "[dap]",
    "# Path inside the container / remote server",
    "# remote=/app",
    "# Path on the local machine (leave empty to use cwd)",
    "# local=",
    "",
  }, "\n")

  local f = io.open(conf_path, "w")
  if not f then
    vim.notify("ConfigInit: cannot write " .. conf_path, vim.log.levels.ERROR)
    return
  end
  f:write(template)
  f:close()

  vim.notify("Created " .. conf_path, vim.log.levels.INFO)
  vim.cmd("edit " .. conf_path)
end

vim.api.nvim_create_user_command("ConfigInit", function() M.init() end, {
  desc = "Create .nvim/editor.conf in the current project",
})

vim.api.nvim_create_user_command("ConfigReload", function()
  M.reload()
  vim.notify("editor.conf reloaded", vim.log.levels.INFO)
end, {
  desc = "Reload .nvim/editor.conf",
})

return M
